# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tapas/protos/table_selection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tapas.protos import interaction_pb2 as tapas_dot_protos_dot_interaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tapas/protos/table_selection.proto',
  package='language.tapas',
  syntax='proto2',
  serialized_pb=_b('\n\"tapas/protos/table_selection.proto\x12\x0elanguage.tapas\x1a\x1etapas/protos/interaction.proto\"\xe1\x07\n\x0eTableSelection\x12H\n\x0fselected_tokens\x18\x03 \x03(\x0b\x32/.language.tapas.TableSelection.TokenCoordinates\x12S\n\x16model_prediction_stats\x18\x02 \x01(\x0b\x32\x33.language.tapas.TableSelection.ModelPredictionStats\x12\x37\n\x05\x64\x65\x62ug\x18\x64 \x01(\x0b\x32(.language.tapas.TableSelection.DebugInfo\x1aP\n\x10TokenCoordinates\x12\x11\n\trow_index\x18\x01 \x01(\x05\x12\x14\n\x0c\x63olumn_index\x18\x02 \x01(\x05\x12\x13\n\x0btoken_index\x18\x03 \x01(\x05\x1a\x44\n\x1cModelPredictionStatsPerModel\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nis_correct\x18\x02 \x01(\x08\x1a\x8c\x01\n\x1dModelPredictionStatsPerColumn\x12\x0e\n\x06\x63olumn\x18\x03 \x01(\x05\x12[\n\x16model_prediction_stats\x18\x02 \x03(\x0b\x32;.language.tapas.TableSelection.ModelPredictionStatsPerModel\x1a\xd2\x01\n\x14ModelPredictionStats\x12]\n\x17\x63olumn_prediction_stats\x18\x01 \x03(\x0b\x32<.language.tapas.TableSelection.ModelPredictionStatsPerColumn\x12[\n\x16model_prediction_stats\x18\x02 \x03(\x0b\x32;.language.tapas.TableSelection.ModelPredictionStatsPerModel\x1a\x9f\x01\n\tDebugInfo\x12@\n\x07\x63olumns\x18\x01 \x03(\x0b\x32/.language.tapas.TableSelection.DebugInfo.Column\x1aP\n\x06\x43olumn\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05score\x18\x02 \x01(\x01\x12\x13\n\x0bis_selected\x18\x03 \x01(\x08\x12\x13\n\x0bis_required\x18\x04 \x01(\x08\x32Y\n\x13table_selection_ext\x12\x18.language.tapas.Question\x18\xcf\xab\xe0\x89\x01 \x01(\x0b\x32\x1e.language.tapas.TableSelection')
  ,
  dependencies=[tapas_dot_protos_dot_interaction__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TABLESELECTION_TOKENCOORDINATES = _descriptor.Descriptor(
  name='TokenCoordinates',
  full_name='language.tapas.TableSelection.TokenCoordinates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row_index', full_name='language.tapas.TableSelection.TokenCoordinates.row_index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='column_index', full_name='language.tapas.TableSelection.TokenCoordinates.column_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token_index', full_name='language.tapas.TableSelection.TokenCoordinates.token_index', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=401,
)

_TABLESELECTION_MODELPREDICTIONSTATSPERMODEL = _descriptor.Descriptor(
  name='ModelPredictionStatsPerModel',
  full_name='language.tapas.TableSelection.ModelPredictionStatsPerModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_id', full_name='language.tapas.TableSelection.ModelPredictionStatsPerModel.model_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_correct', full_name='language.tapas.TableSelection.ModelPredictionStatsPerModel.is_correct', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=471,
)

_TABLESELECTION_MODELPREDICTIONSTATSPERCOLUMN = _descriptor.Descriptor(
  name='ModelPredictionStatsPerColumn',
  full_name='language.tapas.TableSelection.ModelPredictionStatsPerColumn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column', full_name='language.tapas.TableSelection.ModelPredictionStatsPerColumn.column', index=0,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_prediction_stats', full_name='language.tapas.TableSelection.ModelPredictionStatsPerColumn.model_prediction_stats', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=614,
)

_TABLESELECTION_MODELPREDICTIONSTATS = _descriptor.Descriptor(
  name='ModelPredictionStats',
  full_name='language.tapas.TableSelection.ModelPredictionStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='column_prediction_stats', full_name='language.tapas.TableSelection.ModelPredictionStats.column_prediction_stats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_prediction_stats', full_name='language.tapas.TableSelection.ModelPredictionStats.model_prediction_stats', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=827,
)

_TABLESELECTION_DEBUGINFO_COLUMN = _descriptor.Descriptor(
  name='Column',
  full_name='language.tapas.TableSelection.DebugInfo.Column',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='language.tapas.TableSelection.DebugInfo.Column.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='language.tapas.TableSelection.DebugInfo.Column.score', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_selected', full_name='language.tapas.TableSelection.DebugInfo.Column.is_selected', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_required', full_name='language.tapas.TableSelection.DebugInfo.Column.is_required', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=909,
  serialized_end=989,
)

_TABLESELECTION_DEBUGINFO = _descriptor.Descriptor(
  name='DebugInfo',
  full_name='language.tapas.TableSelection.DebugInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columns', full_name='language.tapas.TableSelection.DebugInfo.columns', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TABLESELECTION_DEBUGINFO_COLUMN, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=830,
  serialized_end=989,
)

_TABLESELECTION = _descriptor.Descriptor(
  name='TableSelection',
  full_name='language.tapas.TableSelection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='selected_tokens', full_name='language.tapas.TableSelection.selected_tokens', index=0,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_prediction_stats', full_name='language.tapas.TableSelection.model_prediction_stats', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='debug', full_name='language.tapas.TableSelection.debug', index=2,
      number=100, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    _descriptor.FieldDescriptor(
      name='table_selection_ext', full_name='language.tapas.TableSelection.table_selection_ext', index=0,
      number=288888271, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[_TABLESELECTION_TOKENCOORDINATES, _TABLESELECTION_MODELPREDICTIONSTATSPERMODEL, _TABLESELECTION_MODELPREDICTIONSTATSPERCOLUMN, _TABLESELECTION_MODELPREDICTIONSTATS, _TABLESELECTION_DEBUGINFO, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=1080,
)

_TABLESELECTION_TOKENCOORDINATES.containing_type = _TABLESELECTION
_TABLESELECTION_MODELPREDICTIONSTATSPERMODEL.containing_type = _TABLESELECTION
_TABLESELECTION_MODELPREDICTIONSTATSPERCOLUMN.fields_by_name['model_prediction_stats'].message_type = _TABLESELECTION_MODELPREDICTIONSTATSPERMODEL
_TABLESELECTION_MODELPREDICTIONSTATSPERCOLUMN.containing_type = _TABLESELECTION
_TABLESELECTION_MODELPREDICTIONSTATS.fields_by_name['column_prediction_stats'].message_type = _TABLESELECTION_MODELPREDICTIONSTATSPERCOLUMN
_TABLESELECTION_MODELPREDICTIONSTATS.fields_by_name['model_prediction_stats'].message_type = _TABLESELECTION_MODELPREDICTIONSTATSPERMODEL
_TABLESELECTION_MODELPREDICTIONSTATS.containing_type = _TABLESELECTION
_TABLESELECTION_DEBUGINFO_COLUMN.containing_type = _TABLESELECTION_DEBUGINFO
_TABLESELECTION_DEBUGINFO.fields_by_name['columns'].message_type = _TABLESELECTION_DEBUGINFO_COLUMN
_TABLESELECTION_DEBUGINFO.containing_type = _TABLESELECTION
_TABLESELECTION.fields_by_name['selected_tokens'].message_type = _TABLESELECTION_TOKENCOORDINATES
_TABLESELECTION.fields_by_name['model_prediction_stats'].message_type = _TABLESELECTION_MODELPREDICTIONSTATS
_TABLESELECTION.fields_by_name['debug'].message_type = _TABLESELECTION_DEBUGINFO
DESCRIPTOR.message_types_by_name['TableSelection'] = _TABLESELECTION

TableSelection = _reflection.GeneratedProtocolMessageType('TableSelection', (_message.Message,), dict(

  TokenCoordinates = _reflection.GeneratedProtocolMessageType('TokenCoordinates', (_message.Message,), dict(
    DESCRIPTOR = _TABLESELECTION_TOKENCOORDINATES,
    __module__ = 'tapas.protos.table_selection_pb2'
    # @@protoc_insertion_point(class_scope:language.tapas.TableSelection.TokenCoordinates)
    ))
  ,

  ModelPredictionStatsPerModel = _reflection.GeneratedProtocolMessageType('ModelPredictionStatsPerModel', (_message.Message,), dict(
    DESCRIPTOR = _TABLESELECTION_MODELPREDICTIONSTATSPERMODEL,
    __module__ = 'tapas.protos.table_selection_pb2'
    # @@protoc_insertion_point(class_scope:language.tapas.TableSelection.ModelPredictionStatsPerModel)
    ))
  ,

  ModelPredictionStatsPerColumn = _reflection.GeneratedProtocolMessageType('ModelPredictionStatsPerColumn', (_message.Message,), dict(
    DESCRIPTOR = _TABLESELECTION_MODELPREDICTIONSTATSPERCOLUMN,
    __module__ = 'tapas.protos.table_selection_pb2'
    # @@protoc_insertion_point(class_scope:language.tapas.TableSelection.ModelPredictionStatsPerColumn)
    ))
  ,

  ModelPredictionStats = _reflection.GeneratedProtocolMessageType('ModelPredictionStats', (_message.Message,), dict(
    DESCRIPTOR = _TABLESELECTION_MODELPREDICTIONSTATS,
    __module__ = 'tapas.protos.table_selection_pb2'
    # @@protoc_insertion_point(class_scope:language.tapas.TableSelection.ModelPredictionStats)
    ))
  ,

  DebugInfo = _reflection.GeneratedProtocolMessageType('DebugInfo', (_message.Message,), dict(

    Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), dict(
      DESCRIPTOR = _TABLESELECTION_DEBUGINFO_COLUMN,
      __module__ = 'tapas.protos.table_selection_pb2'
      # @@protoc_insertion_point(class_scope:language.tapas.TableSelection.DebugInfo.Column)
      ))
    ,
    DESCRIPTOR = _TABLESELECTION_DEBUGINFO,
    __module__ = 'tapas.protos.table_selection_pb2'
    # @@protoc_insertion_point(class_scope:language.tapas.TableSelection.DebugInfo)
    ))
  ,
  DESCRIPTOR = _TABLESELECTION,
  __module__ = 'tapas.protos.table_selection_pb2'
  # @@protoc_insertion_point(class_scope:language.tapas.TableSelection)
  ))
_sym_db.RegisterMessage(TableSelection)
_sym_db.RegisterMessage(TableSelection.TokenCoordinates)
_sym_db.RegisterMessage(TableSelection.ModelPredictionStatsPerModel)
_sym_db.RegisterMessage(TableSelection.ModelPredictionStatsPerColumn)
_sym_db.RegisterMessage(TableSelection.ModelPredictionStats)
_sym_db.RegisterMessage(TableSelection.DebugInfo)
_sym_db.RegisterMessage(TableSelection.DebugInfo.Column)

_TABLESELECTION.extensions_by_name['table_selection_ext'].message_type = _TABLESELECTION
tapas_dot_protos_dot_interaction__pb2.Question.RegisterExtension(_TABLESELECTION.extensions_by_name['table_selection_ext'])

# @@protoc_insertion_point(module_scope)
